# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - run: npm install

    - uses: markis/vsce-action@master
      with:
        args: "publish -p $VSCE_TOKEN"
      env:
        # To get a token, follow the instructions here:
        # https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
